import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
    id 'java'
    id 'war'
    id 'org.openapi.generator' version '7.20.0'
    id "com.diffplug.spotless" version "8.4.0"
    id "io.sentry.jvm.gradle" version "6.1.0"
}

group 'com.aws.service'
version '2.0.0'

repositories {
    mavenCentral()
}

ext {
    awsVersion = '2.42.3'
    jUnitJupiterVersion = '6.0.3'
    jUnitPlatformVersion = '6.0.3'
    lombokVersion = '1.18.42'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

dependencies {
    annotationProcessor("org.projectlombok:lombok:${lombokVersion}")
    compileOnly("org.projectlombok:lombok:${lombokVersion}")

    implementation("software.amazon.awssdk:ec2:${awsVersion}")
    implementation("software.amazon.awssdk:elasticloadbalancingv2:${awsVersion}")

    compileOnly("jakarta.validation:jakarta.validation-api:3.1.1")
    compileOnly('jakarta.ws.rs:jakarta.ws.rs-api:4.0.0')
    compileOnly('jakarta.servlet:jakarta.servlet-api:6.1.0')
    compileOnly("jakarta.json.bind:jakarta.json.bind-api:3.0.1")

    implementation("io.smallrye:jandex:3.5.3")
    implementation("org.glassfish.jaxb:jaxb-runtime:4.0.6")

    implementation("com.github.ben-manes.caffeine:caffeine:3.2.3")

    testImplementation("org.junit.jupiter:junit-jupiter-api:${jUnitJupiterVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${jUnitJupiterVersion}")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:${jUnitPlatformVersion}")
    testRuntimeOnly("org.junit.platform:junit-platform-engine:${jUnitPlatformVersion}")

    testImplementation("org.slf4j:slf4j-simple:2.0.17")
    testImplementation("org.wiremock:wiremock:3.13.2")
}

String defaultPackage = "com.aws.service"
tasks.register('openApiGenerateClasses', GenerateTask) {
    String outputDirectory = "${layout.buildDirectory.get()}/generated/JaxRS"

    generatorName.set("jaxrs-spec")
    cleanupOutput.set(true)
    inputSpec.set("$rootDir/swagger/aws-service-hub.yaml")
    templateDir.set("$rootDir/swagger/")
    outputDir.set(outputDirectory)
    invokerPackage.set("${defaultPackage}")
    apiPackage.set("${defaultPackage}.api")
    apiNameSuffix.set("Interface")
    modelPackage.set("${defaultPackage}.model")
    configOptions.set([

            additionalModelTypeAnnotations: "",

            useTags                       : "true",
            dateLibrary                   : "java8",

            openApiSpecFileLocation       : "openapi.yaml",
            sourceFolder                  : "src/main/java",

            useJakartaEe                  : "true",
            useBeanValidation             : "true",
            hideGenerationTimestamp       : "true",
            interfaceOnly                 : "true",

            useSwaggerAnnotations         : "false",

            containerDefaultToNull        : "true",
            openApiNullable               : "false",

            generatePom                   : "false",
            generateConstructorWithAllArgs: "true"
    ])
}


war {
    archiveFileName = 'awsServiceHub.war'
    doFirst {
        def propertyFile = file('build.properties')
        def props = new Properties()
        if (propertyFile.exists()) {
            propertyFile.withReader { props.load(it) }
        }
        props.setProperty('projectName', project.name.toString())
        props.setProperty('releaseDate', new Date().format('yyyy-MM-dd-HH:mm:ss'))
        props.setProperty('projectVersion', version.toString())
        propertyFile.withWriter { props.store(it, null) }
    }
    webInf {
        from('\\') {
            include 'CHANGELOG.md'
            include 'LICENSE.md'
            include 'README.md'
            include 'build.properties'
        }
    }
}

test {
    useJUnitPlatform()
}

spotless {
    java {
        target("**/*.java")
        toggleOffOn()
        palantirJavaFormat()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

afterEvaluate {
    ["build", "war"].each { taskName ->
        tasks.named(taskName) {
            dependsOn("spotlessApply")
        }
    }
}